ports:
- port: 8080
  onOpen: open-preview
image:
  file: Dockerfile.gitpod
  context: .
tasks:
- init: >
    go get -u github.com/golang/protobuf/protoc-gen-go &&
    go get -u google.golang.org/grpc &&
    cd src/github.com/32leaves/ruruku &&
    cd client && yarn install && cd .. &&
    ./build/protoc.sh &&
    cd client && yarn build && cd - &&
    go get -v ./... &&
    go get -v github.com/golang/mock/gomock &&
    go get -v github.com/golang/mock/mockgen &&
    go get -v golang.org/x/tools/cmd/goimports &&
    go get -v github.com/spf13/cobra/cobra &&
    openssl req -new -newkey rsa:4096 -x509 -sha256 -days 365 -nodes -subj "/CN=*/" -out /workspace/server.crt -keyout /workspace/server.key &&
    echo "alias ruruku=\"go run main.go\"" >> ~/.bash_profile &&
    echo "cd /workspace/src/github.com/32leaves/ruruku" >> ~/.bash_profile &&
    echo ". <(ruruku completion)" >> ~/.bash_profile &&
    source ~/.bash_profile
checkoutLocation: src/github.com/32leaves/ruruku
workspaceLocation: .
