cli:
    tlsCert: /workspace/server.crt
server:
    ui:
        enabled: true
        port: 8080
    gRPC:
        enabled: true
        port: 1234
    tls:
        enabled: true
        cert: /workspace/server.crt
        key: /workspace/server.key